name: WakaTimeUpdator

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
jobs:
  updator:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
        with:
          deno-version: 1.1.1
      - uses: actions/checkout@v2

      - name: Update!
        run: deno run --allow-net --allow-read --allow-env index.ts
        env:
          WakaTimeURI: ${{ secrets.WAKATIME }}
          GistId: ${{ secrets.GISTID }}
          GithubToken: ${{ secrets.GITHUBTOKEN }}